owner: CarbonNapkin
repo: upptime

sites:
  - name: CarbonNapkin
    url: https://carbonnapkin.com
    expectedStatusCodes:
      - 200
      - 301
      - 302
      
  - name: API
    url: https://api.carbonnapkin.com
    expectedStatusCodes:
      - 200
      - 301
      - 302
      
  - name: C6NAP
    url: https://c6nap.com
    
  - name: Great Lakes Shafts
    url: https://greatlakesshafts.com
    expectedStatusCodes:
      - 200
      - 301
      - 302

  - name: Lake Superior Fasteners
    url: https://lakesuperiorfasteners.com
    expectedStatusCodes:
      - 200
      - 301
      - 302

status-website:
  cname: status.carbonnapkin.com
  logoUrl: https://carbonnapkin.com/favicon.svg
  name: CarbonNapkin Status
  theme: dark

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  uptime: "*/5 * * * *"
