owner: CarbonNapkin
repo: upptime

sites:
  - name: API
    url: https://api.carbonnapkin.com/health
  - name: Portal
    url: https://portal.carbonnapkin.com/health
  - name: C6NAP
    url: https://c6nap.com/health
  - name: CarbonNapkin
    url: https://carbonnapkin.com/health
  - name: Great Lakes Shafts
    url: https://greatlakesshafts.com/health
  - name: Lake Superior Fasteners
    url: https://lakesuperiorfasteners.com/health

status-website:
  cname: status.carbonnapkin.com
  logoUrl: https://carbonnapkin.com/favicon.svg
  name: CarbonNapkin Status
  themeUrl: https://status.carbonnapkin.com/carbonnapkin-theme.css
  favicon: https://carbonnapkin.com/favicon.svg

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  uptime: "*/5 * * * *"
