name: Static Site CI
on:
  workflow_run:
    workflows: ["Uptime CI"]
    types:
      - completed
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
jobs:
  release:
    name: Build and deploy status website
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Build and deploy
        uses: upptime/uptime-monitor@v1
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT || github.token }}
